INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u1', 'ichibond', 'Ichibond Admin', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'ADMIN', 'Global', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u1', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u1', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u1', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u1', 'PH') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u2', 'jameslee', 'James Lee Admin', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'ADMIN', 'Global', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u2', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u2', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u2', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u2', 'PH') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u3', 'phonghna', 'Phong HNA Admin', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'ADMIN', 'Global', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u3', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u3', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u3', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u3', 'PH') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u4', 'yuspris', 'Yuspris Manager', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'MANAGER', 'DZ', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u4', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u4', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u5', 'katakhanhtrang', 'Kata Khanh Trang Manager', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'MANAGER', 'DZG', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u5', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u6', 'csvietnam', 'CS Vietnam Staff', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'CS', 'DZ', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u6', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u7', 'csindo', 'CS Indo Staff', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'CS', 'DZT', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u7', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u8', 'streamer01', 'Streamer Host VN', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'STREAMER', 'DZG', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u8', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u9', 'streamer02', 'Streamer Host TH', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'STREAMER', 'DZV', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u9', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u10', 'packingsort', 'Packing Warehouse TW', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'PACKING', 'Repair', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u10', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u10', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u10', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u10', 'PH') ON CONFLICT DO NOTHING;
INSERT INTO app_users (user_id, username, display_name, password_hash, role, team_allocation, require_password_change) VALUES ('u11', 'techmaster', 'Tech Repair Master', '$2a$10$X2Ia1z2ImnFOYvXgz1miA.0/cvf3XDX6q2itv4mqHfLuA40bAVgFS', 'TECH', 'Repair', FALSE) ON CONFLICT (username) DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u11', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u11', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u11', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO user_market_access (user_id, market_code) VALUES ('u11', 'PH') ON CONFLICT DO NOTHING;
